---
# StyleLint configuration

extends: stylelint-config-standard
rules:
  at-rule-no-unknown: [
    true,
    ignoreAtRules: ['include', 'extend', 'mixin', 'for', 'if']
  ]
  declaration-colon-space-after: null
  color-hex-case: upper
  color-hex-length: long
  max-empty-lines: 2
  no-descending-specificity: null
