# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: pretty

# Server
source: documentation/end-users
destination: site
host: 0.0.0.0
port: 9001
url:  localhost
encoding: UTF-8

# Custom vars
current_version: 0.1.0
repo: https://stash.ceh.ac.uk/projects/BASWEB/repos/bas-style-kit/browse
issues: https://jira.ceh.ac.uk/browse/BASWEB/component/14697

style_guide_url: https://hackpad.com/BAS-Style-Guide-e0x7fJ4BMsf
feedback_attributes: data-bsk-action="open-feedback-form"
discussions_url: https://hackpad.com/BAS-Style-Guide-Discussions-FG5NNMtG2BI

download:
  source: https://stash.ceh.ac.uk/plugins/servlet/archive/projects/BASWEB/repos/bas-style-kit
  dist: https://s3-eu-west-1.amazonaws.com/packages.calcifer.co/scratch/bas-style-kit/releases/0.0.0/bas-style-kit-dist.zip

cdn:
  css: https://cdn.bas.ac.uk/bas-style-kit/0.0.0/bas-style-kit.min.css
