# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: pretty

# Server
source: documentation/end-users
destination: site
host: 0.0.0.0
port: 9001
url:  localhost
encoding: UTF-8

# Custom vars
current_version: 0.1.0-alpha
repo: https://stash.ceh.ac.uk/projects/BSK/repos/bas-style-kit/browse
issues: https://jira.ceh.ac.uk/browse/BSK

style_guide_url: https://antarctica.hackpad.com/BAS-Style-Guide-NT1D10DRTCo
feedback_attributes: data-bsk-action="open-feedback-form"
discussions_url: https://antarctica.hackpad.com/BAS-Style-Kit-Discussions-zjz6NiUOhdA

download:
  source: https://stash.ceh.ac.uk/plugins/servlet/archive/projects/BSK/repos/bas-style-kit?at=refs%2Ftags%2Fv0.1.0-alpha
  dist: https://bascdnprod.blob.core.windows.net/bas-style-kit/0.1.0-alpha/bas_style_kit_0.1.0-alpha.zip

cdn:
  css: https://az792977.vo.msecnd.net/bas-style-kit/0.1.0-alpha/dist/css/bas-style-kit.min.css
