---
# Jekyll master configuration file

# Additional configuration can be set in files contained in the documentation/end-users/_data directory

# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: pretty

# Server
source: documentation/end-users
destination: site
host: 0.0.0.0
port: 9001
url:  localhost
encoding: UTF-8

# Project vars
repo: https://stash.ceh.ac.uk/projects/BSK/repos/bas-style-kit/browse
issues: https://jira.ceh.ac.uk/browse/BSK
version: 0.1.0-alpha

style_guide_url: https://antarctica.hackpad.com/BAS-Style-Guide-NT1D10DRTCo
feedback_attributes: data-bsk-action="open-feedback-form"
discussions_url: https://antarctica.hackpad.com/BAS-Style-Kit-Discussions-zjz6NiUOhdA

download:
  source: https://stash.ceh.ac.uk/plugins/servlet/archive/projects/BSK/repos/bas-style-kit?at=refs%2Ftags%2Fv0.1.0-alpha
  dist: https://bascdnprod.blob.core.windows.net/bas-style-kit/0.1.0-alpha/bas_style_kit_0.1.0-alpha.zip

cdn:
  bsk-css: https://s3-eu-west-1.amazonaws.com/bas-cdn-prod/bas-style-kit/0.1.0-alpha/dist/css/bas-style-kit.min.css
  bootstrap-bsk-css: https://s3-eu-west-1.amazonaws.com/bas-cdn-prod/bas-style-kit/0.1.0-alpha/dist/css/bootstrap-bsk.min.css

# Google analytics token (each environment uses a different token - dev is not tracked as it isn't a valid FQDN)

analytics_token_prod:  UA-64130716-27
analytics_token_stage: UA-64130716-28

# For development/staging use ".." (not quotes), for production use root with version string "/0.1.0-alpha" (no quotes)
url_base: ..
