# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: pretty

# Server
source: docs
destination: site
host: 0.0.0.0
port: 9001
url:  localhost
encoding: UTF-8

# Custom vars
current_version: 0.1.0
repo: TODO_Project_repository_URL
issues: https://jira.ceh.ac.uk/browse/BASWEB

style_guide_url: https://hackpad.com/BAS-Style-Guide-e0x7fJ4BMsf
feedback_attributes: data-bsk-action="open-feedback-form"

download:
  source: TODO_Project_repository_export_URL
  dist: https://s3-eu-west-1.amazonaws.com/packages.calcifer.co/scratch/bas-style-kit/releases/0.1.0/bas-style-kit-dist.zip

cdn:
  css: https://d2ark1l5l32iip.cloudfront.net/bas-style-kit/0.0.0/bas-style-kit.min.css
