---
version: '2'

services:
  app:
    build: .
    image: docker-registry.data.bas.ac.uk/bsk/bas-style-kit:0.2.0-develop-alpine
    command: gulp develop
    volumes:
      - ./assets:/usr/src/app/assets
      - ./dist:/usr/src/app/dist
      - ./testbed:/usr/src/app/testbed
  web:
    image: nginx:alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/index.html:/usr/share/nginx/html/index.html
      - ./testbed/rendered:/usr/share/nginx/html/testbed
      - ./dist:/usr/share/nginx/html/dist
    ports:
      - "9000:9000"
