---
version: '2'

services:
  app:
    build: .
    image: docker-registry.data.bas.ac.uk/web-apps/bsk/bas-style-kit/app:0.4.0-develop-alpine
    volumes:
      - ./gulpfile.js:/usr/src/app/gulpfile.js
      - ./assets:/usr/src/app/assets
      - ./dist:/usr/src/app/dist

  testbed:
    build: ./testbed
    image: docker-registry.data.bas.ac.uk/web-apps/bsk/bas-style-kit/testbed:0.2.0-develop-alpine
    volumes:
      - ./assets:/usr/src/app/assets
      - ./testbed/src:/usr/src/app/testbed/src
      - ./testbed/public:/usr/src/app/testbed/public
      - ./testbed/gulpfile.js:/usr/src/app/testbed/gulpfile.js

  web:
    image: nginx:alpine
    volumes:
      - ./testbed/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./testbed/public:/usr/share/nginx/html/public
      - ./dist:/usr/share/nginx/html/dist
    ports:
      - "9000:9000"
