---
version: '2'

services:
  app:
    build: .
    image: docker-registry.data.bas.ac.uk/web-apps/bsk/bas-style-kit/app:latest-alpine
    command: ['watch']
    volumes:
      - ./assets:/usr/src/app/assets
      - ./dist:/usr/src/app/dist
      - ./gulpfile.js:/usr/src/app/gulpfile.js
      - ./LICENSE.md:/usr/src/app/LICENSE.md

  testbed:
    build: ./testbed
    image: docker-registry.data.bas.ac.uk/web-apps/bsk/bas-style-kit/testbed:latest-alpine
    command: ['watch']
    volumes:
      - ./package.json:/usr/src/app/package.json
      - ./assets:/usr/src/app/assets
      - ./testbed/src:/usr/src/app/testbed/src
      - ./testbed/public:/usr/src/app/testbed/public
      - ./testbed/gulpfile.js:/usr/src/app/testbed/gulpfile.js
    environment:
      - TESTBED_VERSION=develop

  web:
    image: nginx:alpine
    volumes:
      - ./testbed/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./testbed/nginx/index.html:/usr/share/nginx/html/public/index.html
      - ./testbed/public:/usr/share/nginx/html/public/develop
      - ./dist:/usr/share/nginx/html/public/develop/dist
    ports:
      - "9000:9000"
