---
version: '3'

services:
  app:
    build: .
    image: docker-registry.data.bas.ac.uk/web-apps/bsk/bas-style-kit/app:latest-alpine
    command: ['watch']
    # tty: true
    volumes:
      # - ./node_modules:/usr/src/app/node_modules
      # - ./package.json:/usr/src/app/package.json      
      - ./assets:/usr/src/app/assets
      - ./dist:/usr/src/app/dist
      - ./gulpfile.js:/usr/src/app/gulpfile.js
      - ./webpack.config.js:/usr/src/app/webpack.config.js
      - ./webpack.config.minify.js:/usr/src/app/webpack.config.minify.js
      - ./LICENSE.md:/usr/src/app/LICENSE.md

  testbed:
    build: ./testbed
    image: docker-registry.data.bas.ac.uk/web-apps/bsk/bas-style-kit/testbed:latest-alpine
    command: ['watch']
    # tty: true
    volumes:
      # - ./testbed/package.json:/usr/src/app/testbed/package.json
      - ./package.json:/usr/src/app/package.json
      - ./assets:/usr/src/app/assets
      - ./testbed/lib:/usr/src/app/testbed/lib
      - ./testbed/src:/usr/src/app/testbed/src
      - ./testbed/public:/usr/src/app/testbed/public
      - ./testbed/gulpfile.js:/usr/src/app/testbed/gulpfile.js
    environment:
      - TESTBED_VERSION=develop
    
  webserver:
    image: pierrezemb/gostatic:latest
    ports:
      - 8043:8043
    volumes:
      - ./testbed/index.html:/srv/http/index.html
      - ./testbed/public:/srv/http/develop
      - ./dist:/srv/http/develop/dist




