---

- name: generate firewall service for http-server development webserver - Ubuntu/UFW
  copy:
    src=files/etc/ufw/applications.d/http-server
    dest=/etc/ufw/applications.d/http-server
- name: configure firewall rules for http-server development webserver - Ubuntu/UFW
  ufw:
    name="http-server"
    rule=allow
    direction=in
  notify: Restart Firewall - Ubuntu
