---

- name: setup project deployment environment
  hosts: local
  tasks:
    - name: install jekyll without documentation
      command: "gem install jekyll -v 3.0.0"
    - name: install gulp globally
      command: "npm install --global gulp"
    - name: install node dependencies through npm
      npm: path=.

- name: build and deploy project to staging website
  hosts: local
  tasks:
    - name: run task to clean generated files
      command: gulp clean
    - name: run task to compile less
      command: gulp less
    - name: run task to copy fonts
      command: gulp fonts
    - name: run task to generate jekyll data files for font glyphs
      command: gulp jekyll-data
    - name: build static site using jekyll
      command: jekyll build
      args:
        chdir: ../
