---

- name: setup project deployment environment
  hosts: local
  tasks:
    - name: install jekyll without documentation
      command: "gem install jekyll -v 3.0.0"
    - name: install gulp globally
      command: "npm install --global gulp"
    - name: install node dependencies through npm
      npm: path=.

- name: build and deploy project to production website
  hosts: local
  tasks:
    - name: run task to clean generated files
      command: gulp clean
    - name: run task to compile less
      command: gulp less
    - name: run task to copy fonts
      command: gulp fonts
    - name: run task to generate jekyll data files for font glyphs
      command: gulp jekyll-data
    - name: build static site using jekyll
      command: jekyll build
      args:
        chdir: ../
    - name: copy generated site to temporary location
      command: "cp -a site/. /tmp/{{ project_version }}"
      args:
        chdir: ../
    - name: move the copy into the versions directory of the site for historical access in the future
      shell: "mv /tmp/{{ project_version }}/* site/versions/{{ project_version }}"
      args:
        chdir: ../
