---
# Note: The credentials for calling 's3 Sync' are set automatically by Semaphore within the deployment environment

- name: setup project deployment environment
  hosts: local
  tasks:
    - name: install gulp globally
      command: "npm install --global gulp"
    - name: install node dependencies through npm
      npm: path=.

- name: build and deploy distribution assets to CDN
  hosts: all
  vars:
    - aws_s3_sync_source: "dist"
    - aws_s3_sync_target: "s3://bas-cdn-prod/bas-style-kit/{{ project_version }}/dist"
  tasks:
    - name: run task to clean generated files
      command: gulp clean
    - name: run task to compile less
      command: gulp less
    - name: run task to copy fonts
      command: gulp fonts
    - name: deploy distribution assets to CDN
      command: "aws s3 sync {{ aws_s3_sync_source }} {{ aws_s3_sync_target }}"
      args:
        chdir: ../
