---
# Setup infrastructure and application

- name: setup web-server
  hosts: bas-style-kit-webservers-dev
  remote_user: controller
  sudo: yes
  roles:
    - curl
    - gulp
    - nginx
  tasks:
    # TODO: Move into 'Gulp' role
    - name: install gulp npm package globally
      npm: name=gulp global=yes
    - include: tasks/install-jekyll.yml

- name: complete setup of web-server
  hosts: bas-style-kit-webservers-dev
  remote_user: app
  tasks:
    - name: install node dependencies through npm
      npm: path=/app
