---
# Setup infrastructure for testing project

- name: setup project environment
  hosts: all
  tasks:
    - name: install jekyll without documentation
      command: "gem install jekyll --no-ri --no-rdoc"
    - name: install rouge gem
      command: "gem install rouge"
    - name: install gulp globally
      command: "npm install --global gulp"

- name: configure project environment
  hosts: all
  tasks:
    - name: install node dependencies through npm
      npm: path=.
