---
# Setup infrastructure for testing project

- name: setup project environment and deployment
  hosts: all
  tasks:
    - name: install jekyll without documentation
      command: "gem install jekyll --no-ri --no-rdoc"
    - name: install rouge gem
      command: "gem install rouge"
    - name: install gulp globally
      command: "npm install --global gulp"
    - name: install AWSCLI from pip
      pip: name=awscli

- name: configure project environment and deployment
  hosts: all
  vars_files:
    - vars/aws-cli-auth.yml
  tasks:
    - name: install node dependencies through npm
      npm: path=.
    - name: ensure AWSCLI configuration directory exists
      file: path=~/.aws state=directory
    - name: copy configuration environment file
      copy: src=files/~.aws/aws-cli-config dest=~/.aws/config
    - name: generate credentials environment file
      template: src=templates/~.aws/credentials.j2 dest=~/.aws/credentials mode=0600
