---
# Setup infrastructure and application

- name: prepare web-servers for setup
  hosts: digital-ocean-dev
  remote_user: controller
  sudo: yes
  roles:
    - git
  tasks:
    - name: checkout app from repository app directory
      git: repo="{{ project_repository }}" version=master dest="{{ app_root }}" accept_hostkey=yes
    - name: create directory for SSL certificate
      file: path="/app/provisioning/certificates/star.web.nerc-bas.ac.uk" state=directory
    - name: copy SSL certificate to app directory
      copy: src="certificates/star.web.nerc-bas.ac.uk/star.web.nerc-bas.ac.uk-certificate-including-trust-chain.crt" dest="/app/provisioning/certificates/star.web.nerc-bas.ac.uk/star.web.nerc-bas.ac.uk-certificate-including-trust-chain.crt"
    - name: set owner for app directory
      file: path="{{ app_root }}" owner=app group=app recurse=yes state=directory
    - name: set execute permissions on git-auto-deploy application
      file: path="{{ app_root }}/provisioning/scripts/github-auto-deploy/GitAutoDeploy.py" mode=0775

- name: setup web-servers
  hosts: bas-style-kit-webservers-dev
  remote_user: controller
  sudo: yes
  roles:
    - curl
    - nodejs
    - jekyll
    - nginx
  tasks:
    - name: install gulp npm package globally
      npm: name=gulp global=yes

- name: complete setup of web-servers
  hosts: bas-style-kit-webservers-dev
  remote_user: app
  tasks:
    - name: install node dependencies through npm
      npm: path=/app
    - name: run less compilation gulp task
      command: "gulp less chdir=/app"
    - name: run jekyll build
      shell: "/usr/local/rvm/bin/rvm all do jekyll build chdir={{ app_root }} executable=/bin/bash"
