---
# Setup infrastructure for testing project

- name: setup project environment
  hosts: all
  sudo: yes
  roles:
    - curl
    - gulp
  tasks:
    - name: install gulp npm package globally
      npm: name=gulp global=yes
    - name: install jekyll without documentation
      command: "gem install jekyll --no-ri --no-rdoc"
    - name: install rouge gem
      command: "gem install rouge"

- name: configure project environment
  hosts: all
  tasks:
    - name: install node dependencies through npm
      npm: path=.
