---
# Setup infrastructure for testing project

- name: setup project test environment
  hosts: all
  tasks:
    - name: install jekyll without documentation
      command: "gem install jekyll --no-ri --no-rdoc"
    - name: install rouge gem
      command: "gem install rouge"
    - name: install gulp globally
      command: "npm install --global gulp"
    - name: install node dependencies through npm
      npm: path=.

- name: build and test project
  hosts: all
  tasks:
    - name: run task to check generated files can be cleaned
      command: gulp clean
    # TODO: Check this happens
    - name: run task to check less compiles and CSS lints
      command: gulp less
    # TODO: Check CSS files are created
    - name: run task to check fonts can be copied
      command: gulp fonts
    # TODO: Check this happens
    - name: run task to check jekyll data files for font glyphs can be generated
      command: gulp jekyll-data
    # TODO: Check this happens
    - name: build static site using jekyll
      command: jekyll build
    # TODO: Check this happens
