---
# Setup infrastructure for testing project

- name: setup project test environment
  hosts: local
  tasks:
    - name: install jekyll without documentation
      command: "gem install jekyll -v 3.0.0"
    - name: install gulp globally
      command: "npm install --global gulp"
    - name: install node dependencies through npm
      npm: path=.

- name: build and test project
  hosts: local
  tasks:
    - name: run gulp task to clean generated files can be
      command: gulp clean
    - name: count files in cleaned directory
      shell: "ls dist/ | wc -l"
      register: fact_dist_file_count
      changed_when: false
    - name: assert the number of files in cleaned directory is 0
      assert:
        that:
          - fact_dist_file_count.stdout == "0"
      changed_when: false

    - name: run gulp task to compile less
      command: gulp less
    - name: check if compiled less file was generated
      stat: path=../dist/css/bas-style-kit.css
      register: fact_dist_css_non_min
    - name: check if compiled bootstrap less file was generated
      stat: path=../dist/css/bootstrap-bsk.css
      register: fact_dist_bootstrap_css_non_min
    - name: check if minified compiled less file was generated
      stat: path=../dist/css/bas-style-kit.min.css
      register: fact_dist_css_min
    - name: check if minified compiled bootstrap less file was generated
      stat: path=../dist/css/bootstrap-bsk.min.css
      register: fact_dist_bootstrap_css_min
    - name: assert compiled files were generated
      assert:
        that:
          - fact_dist_css_non_min.stat.exists == True
          - fact_dist_bootstrap_css_non_min.stat.exists == True
          - fact_dist_css_min.stat.exists == True
          - fact_dist_bootstrap_css_min.stat.exists == True

    - name: run gulp task to copy fonts
      command: gulp fonts
    - name: check if devicons font were copied
      stat: path=../dist/fonts/devicons/devicons.woff
      register: fact_dist_font_devicons
    - name: check if font-awesome font were copied
      stat: path=../dist/fonts/font-awesome/fontawesome-webfont.woff
      register: fact_dist_font_fontawesome
    - name: check if gill-sans font were copied
      stat: path=../dist/fonts/gill-sans/2bc69477-90c2-4415-a51f-36e36eee3d5e.woff
      register: fact_dist_font_gillsans
    - name: check if map-glyphs font were copied
      stat: path=../dist/fonts/map-glyphs/MapGlyphs.woff
      register: fact_dist_font_mapglyphs
    - name: check if open-sans font were copied
      stat: path=../dist/fonts/open-sans/Regular/OpenSans-Regular.woff
      register: fact_dist_font_opensans_regular
    - name: assert fonts files were copied
      assert:
        that:
          - fact_dist_font_devicons.stat.exists == True
          - fact_dist_font_fontawesome.stat.exists == True
          - fact_dist_font_gillsans.stat.exists == True
          - fact_dist_font_mapglyphs.stat.exists == True
          - fact_dist_font_opensans_regular.stat.exists == True

    - name: run gulp task to generate iconic font glyph jekyll data-files
      command: gulp jekyll-data
    - name: check if devicons glyph data-file was generated
      stat: path=../documentation/end-users/_data/deviconsicons.yml
      register: fact_jekyll_data_devicons
    - name: check if font-awesome glyph data-file was generated
      stat: path=../documentation/end-users/_data/fontawesomeicons.yml
      register: fact_jekyll_data_fontawesome
    - name: check if map-glyphs glyph data-file was generated
      stat: path=../documentation/end-users/_data/mapglyphsicons.yml
      register: fact_jekyll_data_mapglyphs
    - name: assert jekyll data-files were generated
      assert:
        that:
          - fact_jekyll_data_devicons.stat.exists == True
          - fact_jekyll_data_fontawesome.stat.exists == True
          - fact_jekyll_data_mapglyphs.stat.exists == True

    - name: build static site using jekyll
      command: jekyll build
      args:
        chdir: ../
    - name: check if static site was generated
      stat: path=../site
      register: fact_jekyll_site
    - name: assert jekyll data-files were generated
      assert:
        that:
          - fact_jekyll_site.stat.exists == True
